version: '3'

services:
  db1:
    image: postgres:14
    container_name: postgres1
    ports:
      - 5432:5432
    volumes:
      - db-store1:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  db2:
    image: postgres:14
    container_name: postgres2
    ports:
      - 5433:5432
    volumes:
      - db-store2:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
volumes:
  db-store1:
  db-store2: