version: '3'

services:
  db1:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store1:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  db2:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
volumes:
  db-store1: