/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calendar.reserve.app;
import static spark.Spark.*;

import calendar.reserve.app.controllers.UserController;
import calendar.reserve.app.controllers.ScheduleController;
import calendar.reserve.app.controllers.ReservationController;
import calendar.reserve.app.controllers.LoadController;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        initialize();
        UserController.api();
        ScheduleController.api();
        ReservationController.api();
        LoadController.api();
    }


    private static void initialize() {
        // server port
        port(8090);
    }
}
